url: "https://hoeksemaa.github.io"
baseurl: ""
title: John's homepage
description: Bookmark this to keep an eye on my project updates!

collections:
    projects:
        output: true
        permalink: /projects/:name

markdown: kramdown
theme: minima
