url: "https://hoeksemaa.github.io"
baseurl: ""
title: John's homepage
description: Meandering

collections:
    projects:
        output: true
        permalink: /projects/:name

markdown: kramdown
theme: minima
