url: "https://hoeksemaa.github.io"
baseurl: ""
title: John's homepage
description: Meandering

collections:
    projects:
        output: true
        permalink: /projects/:name

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"

markdown: kramdown
theme: minima
